export const SEARCH_RECIPE = "SEARCH_RECIPE";
export const CHANGE_QUERY = "CHANGE_QUERY";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const SET_HOME_PAGE = "SET_HOME_PAGE";
export const NAVBAR_SEARCH_RECIPE = "NAVBAR_SEARCH_RECIPE";
export const SET_RECIPE = "SET_RECIPE";